---
- hosts: pies
  remote_user: pi
  become: true #disable for specific tasks # WARN actions are running as root
  tasks:

    - name: set the timezone
      timezone:
        name: America/Chicago

    - name: ensure system is up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: install native packages
      apt:
        name:
          - openssl
          - tree
          - vim
          - zsh
          - openssl
          - git
          - python-pip
          - python3-pip
        state: present

    - name: install packages for building python3.7
      apt:
        name: ['build-essential', 'tk-dev', 'libncurses5-dev', 'libncursesw5-dev', 'libreadline6-dev', 'libdb5.3-dev', 'libgdbm-dev', 'libsqlite3-dev', 'libssl-dev', 'libbz2-dev', 'libexpat1-dev', 'liblzma-dev', 'zlib1g-dev', 'libffi-dev']
        state: present


    - name: update pip
      pip:
        name: pip
        state: latest

    - name: install pipenv
      raw: 'pip3 install pipenv' # use pip3

    - name: copy dotfiles to setup shell
      become: false
      copy:
        src: ~/dotfiles
        dest: ~/

    # - name: run setup
    #   become: false
    #   raw: "cd dotfiles; bash setup.sh"
