- hosts: webserver
  become: yes # become super user
  tasks:
    - name: install packages
      apt: pkg={{item}} state=present update_cache=yes
      with_items:
        - python
        - git
        - python-pip

    - name: upgrade pip
      command: "pip install --upgrade pip"

    - name: install pipenv
      command: "pip install --user pipenv"

    - name: git clone repo
      git:
        repo: 'https://github.com/hamidzr/cc-project.git'
        dest: ./project
      register: git_finished
      # when: create.changed
    
    - name: install python dependencies
      command: "chdir=/project/cc-project/server pipenv install"

    - name: start up webserver
      command: "pipenv run python webServer"
